version: '3.8'

services:
  database:
    container_name: api_database
    image: mysql:${DB_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - db_data:/var/lib/mysql

  php:
    container_name: api_php
    build:
      context: .
    ports:
      - '9000:9000'
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off} #set to debug or develop to enable xdebug
      XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST:-no} #set to yes to start xdebug with each request
    volumes:
      - ./:/var/www/project
      #for better performence (but vendor might be not synchronized)
#      - /var/www/project/vendor # ignore vendor folder
      # full app for dev
      - symfony_var:/var/www/project/var

      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database

  nginx:
    container_name: api_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/project:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
# we added volumes with symfony_var for faster I/O (caching, logs, etc.)
volumes:
  symfony_var:
  db_data:
